sudo: required
services:
  - docker

before_install:
  - docker build -t sebastiengoldberg/docker-react -f Dockerfile.dev .

script:
  - docker run sebastiengoldberg/docker-react npm run test -- --coverage
